replicaCount: 1
image:
  repository: nginx
  tag: "1.16" 
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
resources: {}
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
env: dev
configName: "dev-app-config"
# custom:
#   homepageText: "DEV Release: 1.16"