# components:
#   - app: "app-dev"
#     namespace: "dev"
#   - app: "app-qa"
#     namespace: "qa"
components: |
  [
    {
      "app": "app-dev",
      "namespace": "dev"
    },
    {
      "app": "app-qa",
      "namespace": "qa"
    }
  ]