apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-app-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/TanmayRao7/argo-app-of-apps.git
              revision: main
              files:
                - path: appconfig/dev.yaml  # Fetch environment-specific values
          - clusters:
              selector:
                matchLabels:
                  env: '{{ .environment }}'  # Match cluster label with environment from dev.yaml
  # - clusters:
  #     selector:
  #       matchLabels:
  #         env: 'prod'
  template:
    metadata:
      name: 'dev'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true        
      sources:
        - repoURL: https://github.com/TanmayRao7/app-of-apps-v2.git
          targetRevision: main
          path: helm-charts
          helm:
            valueFiles:
              #- ../appconfig/{{ .valuesFile }}  # Dynamically pick values-dev.yaml
            - ../appconfig/values-dev.yaml
      destination:
        server: '{{ .server }}'
        namespace: 'dev'
