apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-app-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/TanmayRao7/argo-app-of-apps.git
              revision: main
              files:
                - path: appconfig/dev.yaml
          - list:
              elementsYaml: |
                {{ .components | fromJson }}
  template:
    metadata:
      name: "{{ .app }}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true        
      sources:
        - repoURL: https://github.com/TanmayRao7/app-of-apps-v2.git
          targetRevision: main
          path: helm-charts
          helm:
            valueFiles:
            - ../appconfig/{{ .valuesFile }}
      destination:
        server: '{{ .server }}'
        namespace: "{{ .namespace }}"